### ISSUE TITLE
ARM.dmg cannot be installed 

### ISSUE THREAD

**Issue by cvasanthk** [chasebank87/fabric-connector#3]
I'm using Mac OS 14.6.1 Sonoma. I'm interested in the fabric-Obsidian integration using your recently released fabric plugin for Obsidian. 
I have downloaded the obsidian plugin from the community plugin.

Fabric-connector is a prerequisite for the plugin setup. 
Going through the steps to configure, I have some problems going through the step to install fabric connector.

1. There are 5 assets listed. Since I'm on Mac,  I have downloaded the fabric_connectorARM.dmg and tried to install. However, I cannot install the app downloaded by fabric_connectorARM.dmg in Mac. (https://github.com/chasebank87/fabric-connector/releases/download/1.0.5/FabricConnector_ARM64.dmg). 

The error I see is as follows: 
 "“Fabric Connector.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information."

2. so I tried the manual installation, https://github.com/chasebank87/fabric-connector?tab=readme-ov-file#installation
I 'm stuck in step 3 Ensure the paths to the Fabric and YT binaries are correctly set in the code:

I searched and found that the path has to be set in api.py. I suppose this is correct.  so in line 97 and 98 in api.py, I set the path as below:
if sys.platform == "darwin":
    HOME_DIR = os.path.expanduser("~")
    FABRIC_PATH = /Users/abc/go/bin/fabric (HOME_DIR, ".local", "bin", "fabric")
    YT_PATH = /Users/abc/go/bin/yt (HOME_DIR, ".local", "bin", "yt")
    #TS_PATH = os.path.join(HOME_DIR, ".local", "bin", "ts")
    TS_PATH = "whisper"
    TS_OUTPUT_PATH = os.path.join(HOME_DIR, ".local", "ts_output")
    PATTERN_PATH = os.path.join(HOME_DIR, ".config", "fabric", "patterns")
Where is the code available and how does one set the 2 paths > FABRIC_PATH and YT_PATH?

Running the Application , To start the application, run:python main.py
This is supposed to start the system tray application and the FastAPI server. I get the error:
Traceback (most recent call last):
  File "/Users/abc/fabric-connector/main.py", line 6, in <module>
    from macos_app import run
  File "/Users/abc/fabric-connector/macos_app.py", line 1, in <module>
    import rumps
ModuleNotFoundError: No module named 'rumps'

I'm not a developer and hence struggling with the fabric connector set up. Please help.

**Comment by chasebank87** [comment]
Hey! Thanks for the interest, you will find this is true for most open source software. Since we don’t sign these apps with a Mac dev account which costs 99$. But to get around that error if you go to system settings, security and scroll down till you see open app anyways, and the fabric connector should be listed there. Hope this helps!

Cheers

**Comment by cvasanthk** [comment]
Thanks for your response. I tried  in system settings > Privacy & Security,  the profile is set by administrator and cannot change " Allow apps downloaded from App Store and identified developers". 

So , this leaves me to do manual installation. So step 3 needs to be resolved as described earlier.

**Comment by chasebank87** [comment]
Oh this is a work computer? Yeah I’ll have to update the build from source instructions, I never really firmed that up in the readme.Sent from my iPhoneOn Aug 31, 2024, at 3:26 PM, cvasanthk ***@***.***> wrote:﻿
Thanks for your response. I tried  in system settings > Privacy & Security,  the profile is set by administrator and cannot change " Allow apps downloaded from App Store and identified developers".
So , this leaves me to do manual installation. So step 3 needs to be resolved as described earlier.

**Comment by chasebank87** [comment]
In regards to step three that step needs to be removed. But I have a new plugin that does not need fabric or fabric connector installed.It’s not officially released yet so you will have to use Brat to install.Use a frozen version: 1.0.5Use GitHub Repo: https://github.com/chasebank87/mesh-aiSent from my iPhoneOn Aug 31, 2024, at 5:59 PM, Chase Elder ***@***.***> wrote:﻿Oh this is a work computer? Yeah I’ll have to update the build from source instructions, I never really firmed that up in the readme.Sent from my iPhoneOn Aug 31, 2024, at 3:26 PM, cvasanthk ***@***.***> wrote:﻿
Thanks for your response. I tried  in system settings > Privacy & Security,  the profile is set by administrator and cannot change " Allow apps downloaded from App Store and identified developers".
So , this leaves me to do manual installation. So step 3 needs to be resolved as described earlier.

**Comment by chasebank87** [comment]
The new plugin is available in the repo, mesh-ai

Cheers
