### ISSUE TITLE
Cannot run the terminal to open FastAPI serve

### ISSUE THREAD

**Issue by hnmike** [chasebank87/fabric-connector#5]
Problems: When running the application with "run:python main.py"
This is supposed to start the system tray application and the FastAPI server. I get the error:
Traceback (most recent call last):
File "/Users/abc/fabric-connector/main.py", line 6, in
from macos_app import run
File "/Users/abc/fabric-connector/macos_app.py", line 1, in
import rumps
ModuleNotFoundError: No module named 'rumps'
Could you fix this!

**Comment by chasebank87** [comment]
Do you specifically want to build from source or would an executable be okay? If so go to the releases page on the right of the GitHub repository.From there you can download the appropriate file.Sent from my iPhoneOn Sep 4, 2024, at 5:13 AM, Hnmike ***@***.***> wrote:﻿
Problems: When running the application with "run:python main.py"
This is supposed to start the system tray application and the FastAPI server. I get the error:
Traceback (most recent call last):
File "/Users/abc/fabric-connector/main.py", line 6, in
from macos_app import run
File "/Users/abc/fabric-connector/macos_app.py", line 1, in
import rumps
ModuleNotFoundError: No module named 'rumps'
Could you fix this!

**Comment by hnmike** [comment]
Thanks sir, I get this fix now !
