### ISSUE TITLE
Launching Fabric Connectors on windows

### ISSUE THREAD

**Issue by tcambonie** [chasebank87/fabric-connector#6]
Hi, 

I used the .exe installer for windows. After launching it, I checked with the task management tool that it is working.
![image](https://github.com/user-attachments/assets/413a7010-0d6e-437c-85b8-16f9b7619d48)

My problem lies next. I don't find the mentionned brain icon. As a result I can't copy the API URL and API key. 
What am i supposed to do in this case ?

Best regards,

Tristan

**Comment by chasebank87** [comment]
The Brain icon should be in the toolbar, but there is a bug right now where it only shows up as white so when using light mode it very hard to see.Sent from my iPhoneOn Sep 12, 2024, at 4:46 AM, tcambonie ***@***.***> wrote:﻿
Hi,
I used the .exe installer for windows. After launching it, I checked with the task management tool that it is working.
image.png (view on web)
My problem lies next. I don't find the mentionned brain icon. As a result I can't copy the API URL and API key.
What am i supposed to do in this case ?
Best regards,
Tristan

**Comment by tcambonie** [comment]
Hi thank you for answering so quickly !
I changed my theme to dark mode, but I still don't find the brain icon.
Down below a screen shot. 
![FabricConnectorBlanIcon](https://github.com/user-attachments/assets/5f103d38-a251-4ed0-9ac4-fac6f4f28771)

Best regards, 

Tristan

**Comment by chasebank87** [comment]
Not there, it’s in tne system tray. Sorry haven’t used windows as a daily driver so I should have used better description for that.Sent from my iPhoneOn Sep 13, 2024, at 3:39 AM, tcambonie ***@***.***> wrote:﻿
Hi thank you for answering so quickly !
I changed my theme to dark mode, but I still don't find the brain icon.
Down below a screen shot.
FabricConnectorBlanIcon.png (view on web)
Best regards,
Tristan

**Comment by tcambonie** [comment]
Thank you very much for your answer !
I have found what was already working !
Keep up your awsome work ;-)
